base:
  params_file: params.yaml
  random_state: 42
data:
  X_test_path: ./data/processed/X_test.csv
  X_train_path: ./data/processed/X_train.csv
  external_data_path: ./data/raw
  interim_data_path: ./data/interim/preprocessed_data.csv
  processed_data_path: ./data/processed
  raw_data_path: ./data/raw_full/data.csv
  test_size: 0.2
  y_test_path: ./data/processed/y_test.csv
  y_train_path: ./data/processed/y_train.csv
mlflow:
  experiment_name: Apartment Rent Regression
  tracking_uri: http://127.0.0.1:5000
  last_run_id: a85da0e013ce49df8f5d79dd7efcef14
  log_experiment: true
reports:
  images_path: ./reports/figures
train:
  dataset_mean:
    bathrooms: 1.4497108436784227
    bedrooms: 1.7433152373359655
    square_feet: 960.6086582387406
    latitude: 36.95384167014666
    longitude: -91.47973707528189
    has_photo_Thumbnail: 0.34308998645963834
    has_photo_Yes: 0.5638738088910823
    pets_allowed_Cats,Dogs: 0.3733596547840502
    pets_allowed_Cats,Dogs,None: 1.2654543613884565e-05
    pets_allowed_Dogs: 0.0012021816433190338
    pets_allowed_unknown: 0.6071143844197259
  dataset_std:
    bathrooms: 0.5487272576240166
    bedrooms: 0.7387245300082385
    square_feet: 427.33350442648026
    latitude: 4.598555203970112
    longitude: 15.770153369902438
    has_photo_Thumbnail: 0.474744246682753
    has_photo_Yes: 0.49590649177462914
    pets_allowed_Cats,Dogs: 0.48369947662387036
    pets_allowed_Cats,Dogs,None: 0.003557322534418908
    pets_allowed_Dogs: 0.0346518628298532
    pets_allowed_unknown: 0.4883948475697584
  model_name: XGBRegressor
  model_path: ./models/model.pkl
  models:
    XGBRegressor:
      learning_rate: 0.15
      min_child_weight: 3
      max_depth: 7
      n_estimators: 2000
      random_state: 42
    RandomForestRegressor:
      n_estimators: 100
      min_samples_split: 2
      min_samples_leaf: 3
      max_features: 9
      max_depth: 40
      random_state: 42
    CatBoostRegressor:
      iterations: 100
      learning_rate: 1
      depth: 16
reproduction:
  reproduction_path: ./reproduction
