base:
  params_file: params.yaml
  random_state: 42
data:
  X_test_path: ./data/processed/X_test.csv
  X_train_path: ./data/processed/X_train.csv
  external_data_path: ./data/raw
  interim_data_path: ./data/interim/preprocessed_data.csv
  processed_data_path: ./data/processed
  raw_data_path: ./data/raw_full/data.csv
  test_size: 0.2
  y_test_path: ./data/processed/y_test.csv
  y_train_path: ./data/processed/y_train.csv
mlflow:
  experiment_name: Apartment Rent Regression
  tracking_uri: http://127.0.0.1:5000
  last_run_id: a85da0e013ce49df8f5d79dd7efcef14
  log_experiment: false
reports:
  images_path: ./reports/figures
train:
  dataset_mean:
    bathrooms: 1.44971084
    bedrooms: 1.74331524
    square_feet: 960.60865824
    latitude: 36.95384167
    longitude: -91.47973708
    has_photo_Thumbnail: 0.34308999
    has_photo_Yes: 0.56387381
    pets_allowed_Cats,Dogs: 0.37335965
    pets_allowed_Cats,Dogs,None: 1.265e-05
    pets_allowed_Dogs: 0.00120218
    pets_allowed_unknown: 0.60711438
  dataset_std:
    bathrooms: 0.54872726
    bedrooms: 0.73872453
    square_feet: 427.33350443
    latitude: 4.5985552
    longitude: 15.77015337
    has_photo_Thumbnail: 0.47474425
    has_photo_Yes: 0.49590649
    pets_allowed_Cats,Dogs: 0.48369948
    pets_allowed_Cats,Dogs,None: 0.00355732
    pets_allowed_Dogs: 0.03465186
    pets_allowed_unknown: 0.48839485
  model_name: RandomForestRegressor
  model_path: ./models/model.pkl
  models:
    XGBRegressor:
      learning_rate: 0.15
      min_child_weight: 3
      max_depth: 7
      n_estimators: 2000
      random_state: 42
    RandomForestRegressor:
      n_estimators: 100
      min_samples_split: 2
      min_samples_leaf: 3
      max_features: 9
      max_depth: 40
      random_state: 42
    CatBoostRegressor:
      iterations: 100
      learning_rate: 1
      depth: 16
reproduction:
  reproduction_path: ./reproduction
onnx:
  onnx_model_path: ./models/model.onnx
