base:
  params_file: params.yaml
  random_state: 42
data:
  X_test_path: ./data/processed/X_test.csv
  X_train_path: ./data/processed/X_train.csv
  external_data_path: ./data/raw
  interim_data_path: ./data/interim/preprocessed_data.csv
  processed_data_path: ./data/processed
  raw_data_path: ./data/raw_full/data.csv
  test_size: 0.2
  y_test_path: ./data/processed/y_test.csv
  y_train_path: ./data/processed/y_train.csv
mlflow:
  experiment_name: Apartment Rent Regression
  tracking_uri: http://127.0.0.1:5000
  last_run_id: a85da0e013ce49df8f5d79dd7efcef14
  log_experiment: false
reports:
  images_path: ./reports/figures
train:
  dataset_mean:
    bathrooms: 1.44955133
    bedrooms: 1.74307375
    square_feet: 959.15218134
    latitude: 36.95684732
    longitude: -91.48026723
    has_photo_Thumbnail: 0.3426738
    has_photo_Yes: 0.56449102
    pets_allowed_CatsDogs: 0.37389731
    pets_allowed_CatsDogsNone: 1.266e-05
    pets_allowed_Dogs: 0.00121502
    pets_allowed_unknown: 0.60661174
  dataset_std:
    bathrooms: 0.54832778
    bedrooms: 0.73935424
    square_feet: 389.34151967
    latitude: 4.6022331
    longitude: 15.77415241
    has_photo_Thumbnail: 0.47460649
    has_photo_Yes: 0.4958266
    pets_allowed_CatsDogs: 0.48383993
    pets_allowed_CatsDogsNone: 0.00355759
    pets_allowed_Dogs: 0.03483618
    pets_allowed_unknown: 0.48850482
  model_name: RandomForestRegressor
  model_path: ./models/model.pkl
  models:
    XGBRegressor:
      learning_rate: 0.15
      min_child_weight: 3
      max_depth: 7
      n_estimators: 2000
      random_state: 42
    RandomForestRegressor:
      n_estimators: 100
      min_samples_split: 2
      min_samples_leaf: 3
      max_features: 9
      max_depth: 40
      random_state: 42
    CatBoostRegressor:
      iterations: 100
      learning_rate: 1
      depth: 16
reproduction:
  reproduction_path: ./reproduction
onnx:
  onnx_model_path: ./models/model.onnx
